/** 
 *  Copyright © 2016 Red Sqirl, Ltd. All rights reserved.
 *  Red Sqirl, Clarendon House, 34 Clarendon St., Dublin 2. Ireland
 *
 *  This file is part of Red Sqirl
 *
 *  User agrees that use of this software is governed by: 
 *  (1) the applicable user limitations and specified terms and conditions of 
 *      the license agreement which has been entered into with Red Sqirl; and 
 *  (2) the proprietary and restricted rights notices included in this software.
 *  
 *  WARNING: THE PROPRIETARY INFORMATION OF Red Sqirl IS PROTECTED BY IRISH AND 
 *  INTERNATIONAL LAW.  UNAUTHORISED REPRODUCTION, DISTRIBUTION OR ANY PORTION
 *  OF IT, MAY RESULT IN CIVIL AND/OR CRIMINAL PENALTIES.
 *  
 *  If you have received this software in error please contact Red Sqirl at 
 *  support@redsqirl.com
 */

package com.redsqirl.workflow.server.action;


import java.io.File;
import java.rmi.RemoteException;
import java.util.List;
import java.util.Map;

import org.w3c.dom.Document;
import org.w3c.dom.Element;

import com.redsqirl.workflow.server.DataOutput;
import com.redsqirl.workflow.server.connect.interfaces.DataStore;

public class OutputActionTest extends DataOutput{

	/**
	 * 
	 */
	private static final long serialVersionUID = -1198299149815581123L;


	public OutputActionTest() throws RemoteException {
		super();
		// TODO Auto-generated constructor stub
	}


	@Override
	public String[] getExtensions() throws RemoteException {
		// TODO Auto-generated method stub
		return null;
	}


	@Override
	public String getTypeName() throws RemoteException {
		// TODO Auto-generated method stub
		return null;
	}


	@Override
	public String getBrowserName() throws RemoteException {
		// TODO Auto-generated method stub
		return null;
	}


	@Override
	public DataStore getBrowser() throws RemoteException {
		// TODO Auto-generated method stub
		return null;
	}


	@Override
	public String generatePathStr(String component, String outputName) throws RemoteException {
		// TODO Auto-generated method stub
		return null;
	}


	@Override
	public void moveTo(String path) throws RemoteException {
		// TODO Auto-generated method stub
		
	}


	@Override
	public void copyTo(String path) throws RemoteException {
		// TODO Auto-generated method stub
		
	}


	@Override
	public String isPathValid(String path) throws RemoteException {
		// TODO Auto-generated method stub
		return null;
	}


	@Override
	public boolean isPathAutoGeneratedForUser(String component, String outputName) throws RemoteException {
		// TODO Auto-generated method stub
		return false;
	}


	@Override
	public void removeAllDataUnderGeneratePath() throws RemoteException {
		// TODO Auto-generated method stub
		
	}


	@Override
	public boolean oozieRemove(Document oozieDoc, Element action, File localDirectory, String pathFromOozieDir,
			String fileNameWithoutExtension) throws RemoteException {
		// TODO Auto-generated method stub
		return false;
	}


	@Override
	public List<Map<String, String>> select(int maxToRead) throws RemoteException {
		// TODO Auto-generated method stub
		return null;
	}


	@Override
	protected boolean exists() throws RemoteException {
		// TODO Auto-generated method stub
		return false;
	}


	@Override
	protected boolean isPathAutoGeneratedForUser(String path) throws RemoteException {
		// TODO Auto-generated method stub
		return false;
	}


	@Override
	protected String rm() throws RemoteException {
		// TODO Auto-generated method stub
		return null;
	}


	@Override
	protected String getDefaultColor() {
		// TODO Auto-generated method stub
		return null;
	}

}
